export const modal = document.getElementById('playerModal');
export const playerListSection = document.getElementById('playerListSection');
export const playerRolesSection = document.getElementById("playerRolesSection");
export const goalkeepersSection = document.querySelector(".modal-player-list.goalkeepers");
export const defendersSection = document.querySelector(".modal-player-list.defenders");
export const midfieldersSection = document.querySelector(".modal-player-list.midfielders");
export const forwardsSection = document.querySelector(".modal-player-list.forwards");
export const playerSearchInput = document.getElementById('playerSearchInput');
export const playerSearchResults = document.getElementById('playerSearchResults');
export const profileGoalkeepersSection = document.querySelector(".modal-profile-list.profile-goalkeepers");
export const profileCenterBacksSection = document.querySelector(".modal-profile-list.profile-center-backs");
export const profileFullBacksSection = document.querySelector(".modal-profile-list.profile-full-backs");
export const profileMidfieldersSection = document.querySelector(".modal-profile-list.profile-midfielders");
export const profileWingersSection = document.querySelector(".modal-profile-list.profile-wingers");
export const profileForwardsSection = document.querySelector(".modal-profile-list.profile-forwards");
export const formationSelect = document.getElementById('formation-select');
export const allSlots = document.querySelectorAll('.position-slot, .bench-slot');
export const allPositionSlots = document.querySelectorAll('.position-slot');
export const allBenchSlots = document.querySelectorAll('.bench-slot');
export const teamNameInput = document.getElementById('team-name');
export const shareButton = document.querySelector('.share-btn');
export const shareModal = document.getElementById('shareModal');
export const closeShareModalButton = document.querySelector('#shareModal .close-btn');
export const downloadImageBtn = document.getElementById('downloadImageBtn');
export const twitterShareBtn = document.getElementById('twitterShareBtn');
export const facebookShareBtn = document.getElementById('facebookShareBtn');
export const copyImageLinkBtn = document.getElementById('copyImageLinkBtn');
export const generatedImageView = document.getElementById('generatedImageView');

export const playersTabBtn = document.getElementById('playersTabBtn');
export const rolesTabBtn = document.getElementById('rolesTabBtn');
export const controlPanelPlayersTabBtn = document.querySelector('.control-panel .tab-btn[data-tab="players"]');
export const closeModalButton = document.querySelector('.close-btn');
export const leagueSelect = document.getElementById("league-select");
export const teamSelect = document.getElementById("team-select");

export const controlPanelTabBtns = document.querySelectorAll('.tab-header .tab-btn');
export const tabPanes = document.querySelectorAll('.tab-panel');
export const profileSectionHeaders = document.querySelectorAll('.profile-section-header');
export const modalProfileCategoryToggleIcons = document.querySelectorAll('.modal-profile-category .toggle-icon');
export const pitchContainer = document.getElementById('pitch-container');
export const loadingSpinner = document.getElementById('loading-spinner');

export const controlPanel = document.getElementById('controlPanel');
export const benchSection = document.getElementById('benchSection');
export const controlPanelToggleBtn = document.getElementById('controlPanelToggleBtn');
export const benchToggleBtn = document.getElementById('benchToggleBtn');